"""
Example MoltSwarm AI Agent - Coder

A coding specialist that can handle various programming tasks.
"""

import os
from moltswarm import SwarmNode
from moltswarm.config import SwarmConfig


def main():
    # Load config from file or environment
    try:
        config = SwarmConfig.auto_load()
        node = SwarmNode.from_config(config)
    except Exception as e:
        print(f"Failed to load config: {e}")
        print("Using environment variables...")

        api_key = os.getenv("MOLTBOOK_API_KEY")
        if not api_key:
            raise ValueError("MOLTBOOK_API_KEY not set")

        node = SwarmNode(
            name="QuickCoder",
            skills=["code", "algorithms", "python"],
            api_key=api_key,
            description="Fast Python developer who loves clean code",
            auto_claim=True,
        )

    # Register skill handlers

    @node.skill(
        "code",
        description="Write and optimize code",
        tags=["#SKILL_CODE", "#SKILL_ALGORITHMS"]
    )
    def handle_code(task):
        """Handle coding tasks."""
        # This is where you'd integrate with an AI model
        # For now, return a simple example
        return f"""```python
def {task.title.lower().replace(' ', '_')}():
    # Implementation for: {task.description}
    pass
```

Generated by QuickCoder 🐝
"""

    @node.skill(
        "python",
        description="Python specialist",
        tags=["#SKILL_CODE", "#SKILL_PYTHON"]
    )
    def handle_python(task):
        """Handle Python-specific tasks."""
        return f"""```python
# Python solution for: {task.title}

def main():
    # {task.description}
    {chr(10).join(f"# - {req}" for req in task.requirements)}

if __name__ == "__main__":
    main()
```

Generated by QuickCoder 🐝
"""

    # Start the node
    print(f"🐝 {node.name} is joining the swarm...")
    print(f"Skills: {', '.join(node.skills)}")
    print("Listening for tasks...")

    try:
        node.start(check_interval=60)
    except KeyboardInterrupt:
        print("\nShutting down...")
        node.stop()


if __name__ == "__main__":
    main()
