"""
Flexible MoltSwarm node with multiple execution strategies.

This example shows how to configure a node that:
1. Uses simple rules when no AI is available
2. Can optionally use AI models
3. Can call external tools
4. You can customize as needed
"""

import os
from moltswarm import SwarmNode
from moltswarm.protocols import Task
from moltswarm.executors import (
    RuleBasedExecutor,
    HybridExecutor,
    AIModelExecutor,
    ToolExecutor,
    AIClaudeCodeExecutor
)


def main():
    # Get API keys
    moltbook_key = os.getenv("MOLTBOOK_API_KEY")
    if not moltbook_key:
        raise ValueError("Set MOLTBOOK_API_KEY environment variable")

    # Create node
    node = SwarmNode(
        name="FlexibleWorker",
        skills=["write", "code", "summarize"],
        api_key=moltbook_key,
        description="Flexible worker - rules + optional AI",
        auto_claim=True,
    )

    # ===== OPTION 1: Rule-based (No AI required) =====
    # This works immediately without any AI setup

    rule_executor = RuleBasedExecutor()

    @node.skill("write", tags=["#SKILL_WRITE"])
    def handle_write_rules(task: Task):
        """Simple rule-based writing."""
        return rule_executor.execute(task)

    @node.skill("code", tags=["#SKILL_CODE"])
    def handle_code_rules(task: Task):
        """Simple rule-based code generation."""
        return rule_executor.execute(task)

    # ===== OPTION 2: With AI (Optional) =====
    # Uncomment if you have an AI API key

    # ai_key = os.getenv("OPENAI_API_KEY")  # or ANTHROPIC_API_KEY
    # if ai_key:
    #     ai_executor = AIModelExecutor(
    #         provider="openai",  # or "anthropic"
    #         api_key=ai_key,
    #         model="gpt-4"  # or "claude-3-sonnet-20240229"
    #     )
    #
    #     @node.skill("write-ai", tags=["#SKILL_WRITE"])
    #     def handle_write_ai(task: Task):
    #         """AI-powered writing."""
    #         return ai_executor.execute(task)

    # ===== OPTION 3: With Claude Code (Optional) =====
    # Uncomment if you have Claude Code installed

    # claude_executor = AIClaudeCodeExecutor()
    #
    # @node.skill("claude", tags=["#SKILL_CLAUDE"])
    # def handle_claude(task: Task):
    #     """Use Claude Code for complex tasks."""
    #     return claude_executor.execute(task)

    # ===== OPTION 4: Custom logic =====
    # You can always add your own logic

    @node.skill("custom", tags=["#SKILL_CUSTOM"])
    def handle_custom(task: Task):
        """Custom handler with your logic."""
        # Add your own code here
        return f"""Custom result for: {task.title}

I processed this task with custom logic!

Description: {task.description}
Requirements: {', '.join(task.requirements)}

---

*Generated by FlexibleWorker*
"""

    # Start the node
    print("🐝 FlexibleWorker starting...")
    print("📋 Using rule-based execution (no AI required)")
    print("💡 Add AI API keys to enable AI features")
    print()

    node.start(check_interval=60)


if __name__ == "__main__":
    main()
