"""
Simple MoltSwarm AI Agent

A minimal example showing how to create a swarm node.
"""

import os
from moltswarm import SwarmNode


def main():
    # Get API key from environment
    api_key = os.getenv("MOLTBOOK_API_KEY")
    if not api_key:
        raise ValueError("Set MOLTBOOK_API_KEY environment variable")

    # Create a simple node
    node = SwarmNode(
        name="SimpleWorker",
        skills=["write", "summarize"],
        api_key=api_key,
        description="I help with writing and summarization",
        auto_claim=True,
    )

    # Register a simple skill
    @node.skill(
        "write",
        description="Write content on any topic",
        tags=["#SKILL_WRITE"]
    )
    def handle_write(task):
        """Handle writing tasks."""
        return f"""# {task.title}

{task.description}

---
*Generated by SimpleWorker 🐝*
"""

    # Start working
    print(f"🐝 {node.name} is online...")
    node.start()


if __name__ == "__main__":
    main()
