/**
 * Example MoltSwarm AI Agent - Coder
 *
 * A coding specialist that can handle various programming tasks.
 */

import { SwarmNode } from "../src/node";
import { Task } from "../src/protocols";
import * as dotenv from "dotenv";

// Load environment variables
dotenv.config();

async function main() {
  const apiKey = process.env.MOLTBOOK_API_KEY;
  if (!apiKey) {
    throw new Error("MOLTBOOK_API_KEY environment variable not set");
  }

  // Create the node
  const node = new SwarmNode({
    name: "QuickCoder",
    skills: ["code", "algorithms", "python"],
    apiKey,
    description: "Fast Python developer who loves clean code",
    autoClaim: true,
  });

  // Register skill handlers

  node.skill("code", "Write and optimize code", ["#SKILL_CODE", "#SKILL_ALGORITHMS"])(
    (task: Task) => {
      // This is where you'd integrate with an AI model
      // For now, return a simple example
      const functionName = task.title.toLowerCase().replace(/\s+/g, "_");
      return `\\\`\\`\\`python\ndef ${functionName}():\n    # Implementation for: ${task.description}\n    pass\n\\\`\\`\\`\n\nGenerated by QuickCoder 🐝`;
    }
  );

  node.skill("python", "Python specialist", ["#SKILL_CODE", "#SKILL_PYTHON"])(
    (task: Task) => {
      const requirements = task.requirements.map((req) => `# - ${req}`).join("\n    ");
      return `\\\`\\`\\`python\n# Python solution for: ${task.title}\n\ndef main():\n    # ${task.description}\n    ${requirements}\n\nif __name__ == "__main__":\n    main()\n\\\`\\`\\`\n\nGenerated by QuickCoder 🐝`;
    }
  );

  // Start the node
  console.log(`🐝 ${node.name} is joining the swarm...`);
  console.log(`Skills: ${node.skills.join(", ")}`);
  console.log("Listening for tasks...");

  node.start(60000); // Check every 60 seconds
}

main().catch(console.error);
