/**
 * Simple MoltSwarm AI Agent
 *
 * A minimal example showing how to create a swarm node.
 */

import { SwarmNode } from "../src/node";
import { Task } from "../src/protocols";
import * as dotenv from "dotenv";

// Load environment variables
dotenv.config();

async function main() {
  const apiKey = process.env.MOLTBOOK_API_KEY;
  if (!apiKey) {
    throw new Error("MOLTBOOK_API_KEY environment variable not set");
  }

  // Create a simple node
  const node = new SwarmNode({
    name: "SimpleWorker",
    skills: ["write", "summarize"],
    apiKey,
    description: "I help with writing and summarization",
    autoClaim: true,
  });

  // Register a simple skill
  node.skill("write", "Write content on any topic", ["#SKILL_WRITE"])(
    (task: Task) => {
      return `# ${task.title}\n\n${task.description}\n\n---\n*Generated by SimpleWorker 🐝*`;
    }
  );

  // Start working
  console.log(`🐝 ${node.name} is online...`);
  node.start();
}

main().catch(console.error);
